#!/usr/bin/env bash
# bash script displaying To infinity and beyond indefinitely
# adds sleep 2 in between each iteration of the loop

while true
do
    echo "To infinity and beyond"
    sleep 2
done
