#!/usr/bin/env bash
# Bash script displaying the content of the file /etc/passwd
# Displays the username, user id and home dir path for user

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
