#!/usr/bin/env bash
# Bash script that groups visitors by IP and HTTP status code
# And displays this data using the list format

i="apache-access.log"
awk -F' ' '{ print $1, $9}' $i | sort | uniq -c|sort -nr
