#!/usr/bin/env bash
# Bash script displaying Best School for loop from 1 to 10
# Displays bad luck on the 4th loop iteration
# and good luck on the 8th

i=0

while [ $i -lt 10 ]
do
  if [ $i -eq 3 ]
  then
    echo "bad luck"
  elif [ $i -eq 7 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
