#!/usr/bin/env bash
# Bash script displaying using for loop: the content of the current directory
# In a ls format
# Where only the part of the name after the first dash is displayed

ls=$(ls)

for i in $ls; do
  echo "$i" | cut -d '-' -f2
done
